### ISSUE TITLE
Add support to have words with dash, spaces, etc

### ISSUE THREAD

**Issue by mauricioabreu** [mauricioabreu/go-hangman#10]
A word like "sugar-free" does not work with the current implementation but it should :)

How it should be:

* It must accept dashes, spaces and apostrophes
* The game can't count it as letters. Only a-z characters must count as guesses. Example: if the word is sugar-free, user will not need to guess the dash (hyphen). 
* It should always be "revealed"

**Comment by jrwren** [comment]
I'd like to try this.

**Comment by mauricioabreu** [comment]
Go ahead @jrwren if you need more info I can describe it better.

**Comment by mauricioabreu** [comment]
Thanks @jrwren
