### ISSUE TITLE
Add tests to the HTTP server

### ISSUE THREAD

**Issue by mauricioabreu** [mauricioabreu/go-hangman#15]
Currently we don't have any tests that cover the ReST API.

**Comment by awgreene** [comment]
I can jump on this.

**Comment by mauricioabreu** [comment]
Go ahead @awgreene

**Comment by mauricioabreu** [comment]
Thank you!

**Comment by mauricioabreu** [comment]
Hey @awgreene I hope you are fine! 

Are you on this issue? Do you need any help?

**Comment by awgreene** [comment]
Hello @mauricioabreu, I had some unexpected work pop up so I'm just starting this now. I hope to have a PR in by Wednesday.

**Comment by mauricioabreu** [comment]
@awgreene it is ok 💟 
Take your time :)

**Comment by mauricioabreu** [comment]
Thank you @awgreene 

Closing this issue.
