### ISSUE TITLE
Make it easy to install dependencies

### ISSUE THREAD

**Issue by mauricioabreu** [mauricioabreu/go-hangman#16]
Figure out and create a way to declare the dependencies needed to run this project.
How does the golang community handle dependencies?

**Comment by NemanjaMilosevic** [comment]
Install dep, define your packages in Gopkg.toml and Gopkg.lock

**Comment by mauricioabreu** [comment]
Thanks @NemanjaMilosevic 
Gonna try this out!

**Comment by mauricioabreu** [comment]
Installing:
https://github.com/mauricioabreu/go-hangman/blob/master/README.md#installing

Running the tests:
https://github.com/mauricioabreu/go-hangman/blob/master/CONTRIBUTING.md#running-the-tests
