### ISSUE TITLE
Make the words.txt file be configurable

### ISSUE THREAD

**Issue by mauricioabreu** [mauricioabreu/go-hangman#23]
It is hardcoded in the code. It would be good to have it configurable in the CLI (text interface) and API.

**Comment by noxer** [comment]
I'll take that one.

**Comment by mauricioabreu** [comment]
Cool @noxer 
I don't have a way to assign the issue to you, but go ahead anyways!Thank you!

**Comment by noxer** [comment]
Do you expect the words file to configurable once when starting the API or for each game?

**Comment by mauricioabreu** [comment]
When starting the CLI and API would be enough. What do you think? 

Two examples with two different paths:
```
go run main.go /tmp/database.txt
```
```
go run http/api.go /home/noxer/words.txt
```

**Comment by noxer** [comment]
That makes it easier. In a later iteration, we could support choosing from a list of files.

    go run main.go -words_file /tmp/database.txt

**Comment by mauricioabreu** [comment]
Good idead @noxer after finishing it, I will open a new issue for this idea. Thank you!

**Comment by mauricioabreu** [comment]
Thank you @noxer 
It is working fine :heart:
